#------------------------------------------------------------------------------------------------------------------------------
# Dockerfile to build a Docker image for running the Ghub crevmath Jupyter notebook
#
# Component of: Ghub
# Purpose: Run a Ghub Jupyter Notebook
# Author: Renette Jones-Ivey
# Date: April 2026
#------------------------------------------------------------------------------------------------------------------------------

# ====================================================================
# System Installations
# ====================================================================

FROM anaconda-7_base_image:latest
    
LABEL desc="Ghub crevmath jupyter notebook docker image."

# ====================================================================
# Anaconda-7 Installations
# ====================================================================

WORKDIR /home/ghubuser

COPY ./anaconda/install_conda_environment_and_kernel_from_yml.sh /home/ghubuser/anaconda/install_conda_environment_and_kernel_from_yml.sh
COPY ./anaconda/anaconda-7_earthaccess_environment.yml /home/ghubuser/anaconda/anaconda-7_earthaccess_environment.yml

WORKDIR /home/ghubuser/anaconda

# Install the earthaccess environment and kernel
RUN chmod +x install_conda_environment_and_kernel_from_yml.sh
RUN /bin/bash install_conda_environment_and_kernel_from_yml.sh anaconda-7 earthaccess

# ====================================================================
# Notebook Configurations
# ====================================================================

WORKDIR /home/ghubuser

COPY ./tools/crevmath /home/ghubuser/crevmath
RUN chown -R ghubuser:ghubuser-group /home/ghubuser/crevmath

# User setup
RUN echo -e "ghubuser ALL=(ALL)       NOPASSWD:ALL\n" >> /etc/sudoers

USER ghubuser

RUN jupyter trust /home/ghubuser/crevmath/crevmath.ipynb

WORKDIR /home/ghubuser/crevmath

# Set the command to run the single-user server when the container starts
CMD ["jupyterhub-singleuser"]
